name: learning_management_system
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.19.0
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  intl: any
  image_picker: any
  file_picker: ^8.1.2
  http: ^1.2.2
  flutter_svg: ^1.0.0
  shared_preferences: ^2.3.3
  go_router: ^14.2.6
  dio: ^5.4.0
  url_launcher: ^6.3.1
  freezed_annotation: ^2.4.4
  riverpod_generator: ^2.6.3
  flutter_secure_storage: ^9.2.2
  badges: ^2.0.3
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
  json_annotation: ^4.9.0


  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
