import 'package:freezed_annotation/freezed_annotation.dart';

// The .freezed.dart and .g.dart files will be generated automatically
part 'user.freezed.dart';  // Generated by Freezed
part 'user.g.dart';        // Generated by json_serializable

/// @freezed is an annotation that tells the code generator to create an immutable class
/// It generates:
/// - copyWith method
/// - equality comparisons
/// - toString method
/// - and more
@freezed
class User with _$User {  // _$User is a generated mixin that adds functionality
  /// 'factory' keyword is used here because the actual implementation
  /// will be generated by Freezed. Factory constructors can return
  /// instances of the class that are already created
  const factory User({
    required int id,
    required String firstName,
    required String lastName,
    required String email,
    required String role,
    String? avatar,  // Optional field (can be null)
    
    /// @JsonKey allows us to customize how fields are serialized/deserialized
    /// includeToJson: false means this field won't be included when converting to JSON
    @JsonKey(includeToJson: false) 
    String? token,
  }) = _User;  // _User is the generated implementation class

  /// Another factory constructor specifically for creating User instances
  /// from JSON data. The implementation is generated in user.g.dart
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}