// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GxduGb6eEC0VLUyL941uAkXqm61V8Vk',
    appId: '1:621224393185:web:37a4a80f567bb7cb347aa0',
    messagingSenderId: '621224393185',
    projectId: 'cpadlms',
    authDomain: 'cpadlms.firebaseapp.com',
    storageBucket: 'cpadlms.firebasestorage.app',
    measurementId: 'G-1M18CWKEMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvQZj_AT7zmS5SzPd9iWo6X-qMfbP6rk',
    appId: '1:621224393185:android:8ec9456628174abf347aa0',
    messagingSenderId: '621224393185',
    projectId: 'cpadlms',
    storageBucket: 'cpadlms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_prIgpgdVqxoGuMNpwVLDNwmydSP3tHQ',
    appId: '1:621224393185:ios:b8635907201877f6347aa0',
    messagingSenderId: '621224393185',
    projectId: 'cpadlms',
    storageBucket: 'cpadlms.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_prIgpgdVqxoGuMNpwVLDNwmydSP3tHQ',
    appId: '1:621224393185:ios:b8635907201877f6347aa0',
    messagingSenderId: '621224393185',
    projectId: 'cpadlms',
    storageBucket: 'cpadlms.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7GxduGb6eEC0VLUyL941uAkXqm61V8Vk',
    appId: '1:621224393185:web:19aeb017878d4b26347aa0',
    messagingSenderId: '621224393185',
    projectId: 'cpadlms',
    authDomain: 'cpadlms.firebaseapp.com',
    storageBucket: 'cpadlms.firebasestorage.app',
    measurementId: 'G-F5YXPVF56D',
  );
}
